const defaults=window.YASHMI_CONTENT;let data=defaults;try{data=JSON.parse(localStorage.getItem('yashmi-content'))||defaults}catch(e){}
const $=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function markdown(src){let s=esc(src||'');s=s.replace(/!\[([^\]]*)\]\((https?:\/\/[^\s)]+)\)/g,'<img class="inline-content-image" src="$2" alt="$1" loading="lazy">').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1 ↗</a>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^> (.+)$/gm,'<blockquote>$1</blockquote>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return s.split(/\n\n+/).map(x=>/^<(h2|blockquote|img)/.test(x)?x:`<p>${x.replace(/\n/g,'<br>')}</p>`).join('')};
$('#eyebrow').textContent=data.intro.eyebrow;$('#title').textContent=data.intro.title;$('#dek').textContent=data.intro.dek;$('#status').textContent=data.intro.status;$('#about-copy').textContent=data.about;$('#year').textContent=new Date().getFullYear();
for(const k of ['email','substack','twitter','linkedin']){const href=data.links[k]||'#';$('#'+k).href=href;$('#footer-'+k).href=href}
const dialog=$('#post-dialog'),post=$('#post-content');
function media(url){if(!url)return '';const yt=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([^?&/]+)/);if(yt)return `<div class="post-media"><iframe src="https://www.youtube.com/embed/${esc(yt[1])}" title="Video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>`;return `<a class="external-card" href="${esc(url)}" target="_blank" rel="noopener"><span>Open project</span><strong>${esc(url.replace(/^https?:\/\//,'').split('/')[0])} ↗</strong></a>`}
function openProject(p){post.innerHTML=`<div class="post-kicker">${esc(p.section)} / ${esc(p.type)}${p.year?' / '+esc(p.year):''}</div>${p.image?`<img class="post-image" src="${esc(p.image)}" alt="">`:''}<h2>${esc(p.title)}</h2><p class="post-dek">${esc(p.subtitle)}</p><div class="post-body">${markdown(p.description||p.subtitle)}</div>${media(p.embedUrl||p.link||'')}${p.details?`<div class="post-details"><div class="post-kicker">Notes / tools / stack</div>${esc(p.details).replace(/\n/g,'<br>')}</div>`:''}`;dialog.showModal();document.body.classList.add('modal-open')}
function openNote(n){post.innerHTML=`<div class="post-kicker">Notebook / ${esc(n.date)}</div><h2>${esc(n.title)}</h2><div class="post-body">${markdown(n.fullText||n.text)}</div>`;dialog.showModal();document.body.classList.add('modal-open')}
dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};dialog.onclose=()=>document.body.classList.remove('modal-open');
const rails={work:$('#project-grid'),notes:$('#notes-project-grid'),play:$('#play-grid')};data.projects.forEach((p,i)=>{const a=document.createElement('article'),wordCount=(p.subtitle||'').match(/([\d,]+)\s+words?/i)?.[1],tag=(p.tags||[])[0]||p.type,subtitleRedundant=wordCount&&(p.subtitle||'').toLowerCase().includes(String(tag).toLowerCase());a.className=`project ${p.featured?'featured':''} ${p.color||'paper'}`;a.tabIndex=0;a.setAttribute('role','button');a.setAttribute('aria-label',`Open ${p.title}`);a.innerHTML=`<div class="visual">${p.image?`<img src="${esc(p.image)}" alt="">`:`<span>${String(i+1).padStart(2,'0')}</span><i></i>`}</div><div class="project-copy"><div class="meta"><p>${esc(tag)}${wordCount?' · '+wordCount+' words':''}${p.year?' · '+esc(p.year):''}</p></div><h3>${esc(p.title)}</h3>${subtitleRedundant?'':`<p class="subtitle">${esc(p.subtitle)}</p>`}</div>`;const open=()=>{if(p.id==='research-01')location.href='reader.html?id=research-01';else openProject(p)};a.onclick=open;a.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')open()};(rails[p.section]||rails.work).append(a)});
const nl=$('#notes-list');data.notes.forEach(n=>{const r=document.createElement('article');r.tabIndex=0;r.setAttribute('role','button');r.innerHTML=`<time>${esc(n.date)}</time><div><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p></div>`;r.onclick=()=>openNote(n);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')openNote(n)};nl.append(r)});
function setupRail(id,countId){const rail=$('#'+id),items=[...rail.children],counter=$('#'+countId),buttons=[...document.querySelectorAll(`[data-target="${id}"]`)];const update=()=>{const left=rail.scrollLeft,max=rail.scrollWidth-rail.clientWidth,index=Math.min(items.length-1,Math.max(0,Math.round(left/(items[0]?.getBoundingClientRect().width+18))));counter.textContent=`${String(index+1).padStart(2,'0')} / ${String(items.length).padStart(2,'0')}`;buttons[0].disabled=left<4;buttons[1].disabled=left>max-4};buttons.forEach(b=>b.addEventListener('click',()=>{const left=rail.scrollLeft,step=items[0].getBoundingClientRect().width+18,current=Math.min(items.length-1,Math.max(0,Math.round(left/step))),target=Math.min(items.length-1,Math.max(0,current+(b.classList.contains('next')?1:-1)));items[target].scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}));rail.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update()}
setupRail('project-grid','work-count');setupRail('notes-project-grid','notes-project-count');setupRail('play-grid','play-count');
