let d=structuredClone(YASHMI_RESUME);const e=s=>String(s||'').replace(/[&"]/g,c=>c==='&'?'&amp;':'&quot;'),field=(l,k,v,area=false,full=false)=>`<label class="${full?'full':''}">${l}${area?`<textarea data-key="${k}">${e(v)}</textarea>`:`<input data-key="${k}" value="${e(v)}">`}</label>`;
function base(){document.querySelector('#base').innerHTML=field('Name','name',d.name)+field('Location','location',d.location)+field('Headline','headline',d.headline,true,true)+field('Profile','profile',d.profile,true,true)+field('Phone label','phone',d.phone)+field('Phone link','phoneHref',d.phoneHref)+field('LinkedIn URL','linkedin',d.linkedin)+field('X URL','twitter',d.twitter)+field('Substack URL','substack',d.substack)}
function exps(){document.querySelector('#experience').innerHTML=d.experience.map((x,i)=>`<div class="card"><div class="cardhead"><b>${e(x.title||'New experience')}</b><button type="button" class="remove" data-rx="${i}">Remove</button></div><div class="fields">${['dates','place','title','org'].map(k=>field(k,k,x[k]).replaceAll(`data-key="${k}"`,`data-x="${i}.${k}"`)).join('')}<label class="full">Bullets (one per line)<textarea data-x="${i}.bullets">${e((x.bullets||[]).join('\n'))}</textarea></label>${field('Single-line description','text',x.text||'',true,true).replace('data-key','data-x').replace('"text"',`"${i}.text"`)}${field('Program / note line','note',x.note||'',true,true).replace('data-key','data-x').replace('"note"',`"${i}.note"`)}</div></div>`).join('');bind()}
function edus(){document.querySelector('#education').innerHTML=d.education.map((x,i)=>`<div class="card"><div class="cardhead"><b>${e(x.title)}</b><button type="button" class="remove" data-re="${i}">Remove</button></div><div class="fields">${field('Degree / credential','title',x.title).replace('data-key',`data-ed`).replace('"title"',`"${i}.title"`)}${field('Institution / detail','institution',x.institution).replace('data-key',`data-ed`).replace('"institution"',`"${i}.institution"`)}</div></div>`).join('');bind()}
function other(){document.querySelector('#other').innerHTML=field('Courses','courses',d.courses,true,true)+field('Writing & other','writing',d.writing,true,true)}
function pull(){document.querySelectorAll('[data-key]').forEach(x=>d[x.dataset.key]=x.value);document.querySelectorAll('[data-x]').forEach(x=>{let[i,k]=x.dataset.x.split('.');d.experience[i][k]=k==='bullets'?x.value.split('\n').map(v=>v.trim()).filter(Boolean):x.value});document.querySelectorAll('[data-ed]').forEach(x=>{let[i,k]=x.dataset.ed.split('.');d.education[i][k]=x.value})}
function bind(){document.querySelectorAll('[data-rx]').forEach(b=>b.onclick=()=>{pull();d.experience.splice(+b.dataset.rx,1);exps()});document.querySelectorAll('[data-re]').forEach(b=>b.onclick=()=>{pull();d.education.splice(+b.dataset.re,1);edus()})}
document.querySelector('#add-experience').onclick=()=>{pull();d.experience.push({dates:'',place:'',title:'New role',org:'Organisation',text:'',bullets:[]});exps()};document.querySelector('#add-education').onclick=()=>{pull();d.education.push({title:'New credential',institution:'Institution'});edus()};const statusEl=document.querySelector('#status');document.querySelector('#form').oninput=()=>{statusEl.textContent='Unsaved changes';statusEl.className='save-status'};
document.querySelector('#save').onclick=async()=>{pull();const password=document.querySelector('#editor-password').value;if(!password){statusEl.textContent='Enter editor password';return;}statusEl.textContent='Publishing…';const content='const YASHMI_RESUME='+JSON.stringify(d,null,2)+';\n';try{let r=await fetch(window.SAVE_API||'https://yashmi-editor-api.innovative-newt.workers.dev',{method:'POST',headers:{'Content-Type':'application/json','X-Editor-Password':password},body:JSON.stringify({path:'resume-data.js',content,message:'Update resume content'})}),j=await r.json();if(!r.ok)throw Error(j.error||'Save failed');statusEl.textContent='Published live';statusEl.className='save-status saved'}catch(err){statusEl.textContent=err.message;statusEl.className='save-status'}};base();exps();edus();other();
